version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      libraries:
        patterns:
          - "com.google.guava:guava"
          - "org.apache.commons:commons-lang3"
      spring:
        patterns:
          - "org.springframework.boot:spring-boot-starter-parent"
